name: Dev Container Build Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: echo "Dev container built successfully."
